<p>I have <code>windows service</code> which works on my machine without problem. When I installed it on another machine it <code>throws</code> exception <code>System.IO.FileNotFoundException</code>. The service is run as Local System. The problem is that is does not go inside the body of the thread method. There is no sense to me to throw such kind of exception.</p>  <p>The line of which this happens is. </p>  <pre><code>    Thread action = new Thread( () =&gt; {      try        {          using (SpreadsheetDocument spreadsheetDocument = SpreadsheetDocument.Open(..., false))          {          ...          }          })       }      catch(Exception ex)      {...} </code></pre>  <p>What could be the problem for this exception ?</p>