<p>This is the code sample and I am getting an error "must be caught or declare to be  thrown" but I have</p>  <p>already handled the IOException. So can you please tell why the error is populating. The code also</p>  <p>follows the handle and declare rule.</p>  <pre><code>public void rethrow() throws SQLException, IOException {     try {         couldThrowAnException();     }     catch(Exception e) {         e = new IOException();         throw e;            //Error: must be caught or declare to be thrown     } } </code></pre>