<p>I am using Hibernate as JPA provider and Oracle as database, but while deploying app I am getting </p>  <pre><code>  Caused by: javax.resource.spi.ResourceAllocationException: Error in allocating a connection. Cause: Connection could not be allocated because: java.net.ConnectException : Error connecting to server localhost on port 1527 with message Connection refused: connect.     at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:319)     at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:196)     at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:171)     at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:166)     at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:146)     ... 58 more Caused by: com.sun.appserv.connectors.internal.api.PoolingException: Connection could not be allocated because: java.net.ConnectException : Error connecting to server localhost on port 1527 with message Connection refused: connect.     at com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.addResource(RWLockDataStructure.java:103)     at com.sun.enterprise.resource.pool.ConnectionPool.addResource(ConnectionPool.java:282)     at com.sun.enterprise.resource.pool.ConnectionPool.createResourceAndAddToPool(ConnectionPool.java:1512)     at com.sun.enterprise.resource.pool.ConnectionPool.createResources(ConnectionPool.java:944)     at com.sun.enterprise.resource.pool.ConnectionPool.initPool(ConnectionPool.java:230)     at com.sun.enterprise.resource.pool.ConnectionPool.internalGetResource(ConnectionPool.java:511)     at com.sun.enterprise.resource.pool.ConnectionPool.getResource(ConnectionPool.java:381)     at com.sun.enterprise.resource.pool.PoolManagerImpl.getResourceFromPool(PoolManagerImpl.java:245)     at com.sun.enterprise.resource.pool.PoolManagerImpl.getResource(PoolManagerImpl.java:170)     at com.sun.enterprise.connectors.ConnectionManagerImpl.getResource(ConnectionManagerImpl.java:360)     at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:307)     ... 62 more Caused by: com.sun.appserv.connectors.internal.api.PoolingException: Connection could not be allocated because: java.net.ConnectException : Error connecting to server localhost on port 1527 with message Connection refused: connect.     at com.sun.enterprise.resource.pool.ConnectionPool.createSingleResource(ConnectionPool.java:924)     at com.sun.enterprise.resource.pool.ConnectionPool.createResource(ConnectionPool.java:1189)     at com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.addResource(RWLockDataStructure.java:98)     ... 72 more Caused by: com.sun.appserv.connectors.internal.api.PoolingException: Connection could not be allocated because: java.net.ConnectException : Error connecting to server localhost on port 1527 with message Connection refused: connect.     at com.sun.enterprise.resource.allocator.LocalTxConnectorAllocator.createResource(LocalTxConnectorAllocator.java:110)     at com.sun.enterprise.resource.pool.ConnectionPool.createSingleResource(ConnectionPool.java:907)     ... 74 more Caused by: javax.resource.spi.ResourceAllocationException: Connection could not be allocated because: java.net.ConnectException : Error connecting to server localhost on port 1527 with message Connection refused: connect.     at com.sun.gjc.spi.DSManagedConnectionFactory.createManagedConnection(DSManagedConnectionFactory.java:129)     at com.sun.enterprise.resource.allocator.LocalTxConnectorAllocator.createResource(LocalTxConnectorAllocator.java:87)     ... 75 more Caused by: java.sql.SQLNonTransientConnectionException: java.net.ConnectException : Error connecting to server localhost on port 1527 with message Connection refused: connect.     at org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)     at org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)     at org.apache.derby.jdbc.ClientBaseDataSourceRoot.getConnection(Unknown Source)     at com.sun.gjc.spi.DSManagedConnectionFactory.createManagedConnection(DSManagedConnectionFactory.java:117)     ... 76 more Caused by: org.apache.derby.client.am.DisconnectException: java.net.ConnectException : Error connecting to server localhost on port 1527 with message Connection refused: connect.     at org.apache.derby.client.net.NetAgent.&lt;init&gt;(Unknown Source)     at org.apache.derby.client.net.NetConnection.newAgent_(Unknown Source)     at org.apache.derby.client.am.Connection.initConnection(Unknown Source)     at org.apache.derby.client.am.Connection.&lt;init&gt;(Unknown Source)     at org.apache.derby.client.net.NetConnection.&lt;init&gt;(Unknown Source)     at org.apache.derby.client.net.NetConnection40.&lt;init&gt;(Unknown Source)     at org.apache.derby.client.net.ClientJDBCObjectFactoryImpl40.newNetConnection(Unknown Source)     at org.apache.derby.jdbc.ClientBaseDataSourceRoot.getConnectionX(Unknown Source)     ... 78 more Caused by: java.net.ConnectException: Connection refused: connect     at java.net.DualStackPlainSocketImpl.connect0(Native Method)     at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)     at java.net.Socket.connect(Socket.java:589)     at java.net.Socket.connect(Socket.java:538)     at java.net.Socket.&lt;init&gt;(Socket.java:434)     at java.net.Socket.&lt;init&gt;(Socket.java:211)     at javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:271)     at org.apache.derby.client.net.OpenSocketAction.run(Unknown Source)     at org.apache.derby.client.net.OpenSocketAction.run(Unknown Source)     at java.security.AccessController.doPrivileged(Native Method)     ... 86 more ]] </code></pre>  <p>this error below is my persistence.xml file</p>  <pre><code>&lt;?xml version="1.0" encoding="UTF-8"?&gt; &lt;persistence xmlns="http://xmlns.jcp.org/xml/ns/persistence" version="2.1"&gt;      &lt;persistence-unit name="userweb"&gt;         &lt;provider&gt;org.hibernate.jpa.HibernatePersistenceProvider&lt;/provider&gt;         &lt;properties&gt;             &lt;property name="hibernate.connection.url" value="jdbc:oracle:thin:@server:1521/servicename"/&gt;             &lt;property name="hibernate.connection.driver_class" value="oracle.jdbc.OracleDriver"/&gt;             &lt;property name="hibernate.connection.username" value="testuser"/&gt;             &lt;property name="hibernate.connection.password" value="testpass"/&gt;             &lt;property name="hibernate.show_sql" value="true"/&gt;             &lt;property name="hibernate.dialect" value="org.hibernate.dialect.Oracle10gDialect"/&gt;             &lt;property name="hibernate.hbm2ddl.auto" value="create"/&gt;         &lt;/properties&gt;     &lt;/persistence-unit&gt; &lt;/persistence&gt; </code></pre>  <p>what is going wrong?</p>  <h1>update</h1>  <pre><code>java.io.IOException: com.sun.enterprise.admin.remote.RemoteFailureException: Error occurred during deployment: Exception while preparing the app : [PersistenceUnit: userweb] Unable to build Hibernate SessionFactory. Please see server.log for more details. </code></pre>  <p>getting above error too.</p>