<p>Like others, I'm trying to get the Google refresh token to work in order to run scheduled tasks that copy and rename files. </p>  <p>When I first manually authenticate within a terminal, my url ends in &amp;access_type=offline. However, when I go in and try to manually use gauth.Refresh() in ipython, it fails with the same error as when my credentials file expires: </p>  <pre><code>pydrive.auth.RefreshError: No refresh_token found.Please set access_type of OAuth to offline. </code></pre>  <p>How do I actually set access_type to offline? Any suggestions are greatly appreciated.</p>  <p>I have been <a href="http://stackoverflow.com/questions/24419188/automating-pydrive-verification-process">here</a>, <a href="http://stackoverflow.com/questions/27086905/google-drive-no-refresh-token-found-set-access-type-of-oauth-to-offline">here</a>, and <a href="http://pythonhosted.org/PyDrive/oauth.html?highlight=access" rel="nofollow">here</a> trying to troubleshoot this.</p>  <p>My script:</p>  <pre><code>from pydrive.auth import GoogleAuth from pydrive.drive import GoogleDrive  gauth = GoogleAuth()  # Try to load saved client credentials gauth.LoadCredentialsFile("GoogleDriveCredentials.txt") if gauth.credentials is None:     # Authenticate if they're not there     gauth.LocalWebserverAuth() elif gauth.access_token_expired:     # Refresh them if expired     print "Google Drive Token Expired, Refreshing"     gauth.Refresh() else:     # Initialize the saved creds     gauth.Authorize() # Save the current credentials to a file gauth.SaveCredentialsFile("GoogleDriveCredentials.txt") drive = GoogleDrive(gauth) </code></pre>  <p>My settings.yaml file:</p>  <pre><code>client_config_backend: settings client_config:   client_id: ###actual client_id###   client_secret: ###actual client_secret###  save_credentials: True save_credentials_backend: file save_credentials_file: credentials.json  get_refresh_token: True  oauth_scope:   - https://www.googleapis.com/auth/drive </code></pre>