<p>Can anyone teach me where to insert <strong>try/catch</strong> into this code for making sure it won't crash if user enters a string that isn’t “<strong>Quit</strong>” or also isn’t a number? The following code is used for calculating the average of some numbers. My professor didn't tell us which <strong>exception</strong> we shall use. Also I am not quite familiar with them. </p>  <pre><code>import io.StdIn._  def sumAndCount() : (Int, Int) = {     println("Please enter a number; or enter Quit:")     val input = readLine.toLowerCase.trim     input match {         case "quit" =&gt; (0, 0)         case _ =&gt; val (sum, count) =  sumAndCount()                   (input.toInt+sum, count + 1)     } }  val (sum, count) = sumAndCount() val aver = sum.toDouble/count  println(f"The average is $aver") </code></pre>